/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LeadId = IDL.Nat;
export const DocumentId = IDL.Nat;
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const Document = IDL.Record({
  'id' : DocumentId,
  'fileSize' : IDL.Nat,
  'fileType' : IDL.Text,
  'filename' : IDL.Text,
  'leadId' : LeadId,
  'storageUrl' : IDL.Text,
  'uploadedAt' : Timestamp,
  'uploadedBy' : UserId,
});
export const LeadStatus = IDL.Variant({
  'Won' : IDL.Null,
  'Lost' : IDL.Null,
  'ProposalSent' : IDL.Null,
  'Contacted' : IDL.Null,
  'Qualified' : IDL.Null,
  'FollowUpScheduled' : IDL.Null,
  'NewLead' : IDL.Null,
  'Interested' : IDL.Null,
  'NotInterested' : IDL.Null,
});
export const LeadSource = IDL.Variant({
  'Website' : IDL.Null,
  'ManualEntry' : IDL.Null,
  'LandingPage' : IDL.Null,
  'FacebookAds' : IDL.Null,
  'Other' : IDL.Text,
  'CsvUpload' : IDL.Null,
  'ApiIntegration' : IDL.Null,
  'Referral' : IDL.Null,
  'GoogleAds' : IDL.Null,
});
export const StatusHistoryEntry = IDL.Record({
  'status' : LeadStatus,
  'changedAt' : Timestamp,
  'changedBy' : UserId,
});
export const LeadPublic = IDL.Record({
  'id' : LeadId,
  'status' : LeadStatus,
  'source' : LeadSource,
  'campaign' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'statusHistory' : IDL.Vec(StatusHistoryEntry),
  'email' : IDL.Text,
  'updatedAt' : Timestamp,
  'courseInterest' : IDL.Text,
  'notes' : IDL.Text,
  'dealValue' : IDL.Nat,
  'phone' : IDL.Text,
  'assignedUserId' : IDL.Opt(UserId),
});
export const TaskId = IDL.Nat;
export const RecurringType = IDL.Variant({
  'Weekly' : IDL.Null,
  'None' : IDL.Null,
  'Daily' : IDL.Null,
  'Monthly' : IDL.Null,
});
export const TaskStatus = IDL.Variant({
  'Overdue' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const TaskType = IDL.Variant({
  'Sms' : IDL.Null,
  'Email' : IDL.Null,
  'Call' : IDL.Null,
  'Whatsapp' : IDL.Null,
  'Meeting' : IDL.Null,
});
export const FollowUpTaskPublic = IDL.Record({
  'id' : TaskId,
  'title' : IDL.Text,
  'assignedTo' : UserId,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'recurring' : RecurringType,
  'dueDate' : Timestamp,
  'taskStatus' : TaskStatus,
  'taskType' : TaskType,
  'leadId' : LeadId,
  'nextRunDate' : IDL.Opt(Timestamp),
});
export const CreateTaskInput = IDL.Record({
  'title' : IDL.Text,
  'assignedTo' : UserId,
  'recurring' : RecurringType,
  'dueDate' : Timestamp,
  'taskType' : TaskType,
  'leadId' : LeadId,
});
export const CreateLeadInput = IDL.Record({
  'source' : LeadSource,
  'campaign' : IDL.Text,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'email' : IDL.Text,
  'courseInterest' : IDL.Text,
  'notes' : IDL.Text,
  'dealValue' : IDL.Nat,
  'phone' : IDL.Text,
  'assignedUserId' : IDL.Opt(UserId),
});
export const LeadFilter = IDL.Record({
  'tag' : IDL.Opt(IDL.Text),
  'status' : IDL.Opt(LeadStatus),
  'source' : IDL.Opt(LeadSource),
  'campaign' : IDL.Opt(IDL.Text),
  'toDate' : IDL.Opt(Timestamp),
  'fromDate' : IDL.Opt(Timestamp),
  'assignedUserId' : IDL.Opt(UserId),
});
export const FunnelStage = IDL.Record({
  'status' : LeadStatus,
  'count' : IDL.Nat,
});
export const CounselorStats = IDL.Record({
  'userId' : UserId,
  'totalAssigned' : IDL.Nat,
  'totalFollowedUp' : IDL.Nat,
  'totalConverted' : IDL.Nat,
});
export const LeadStats = IDL.Record({
  'totalLeads' : IDL.Nat,
  'totalDealValue' : IDL.Nat,
  'wonLeads' : IDL.Nat,
  'conversionRate' : IDL.Nat,
  'byStatus' : IDL.Vec(IDL.Tuple(LeadStatus, IDL.Nat)),
  'bySource' : IDL.Vec(IDL.Tuple(LeadSource, IDL.Nat)),
});
export const ActivityId = IDL.Nat;
export const ActivityType = IDL.Variant({
  'TaskCompleted' : IDL.Null,
  'WhatsappSent' : IDL.Null,
  'DocumentUploaded' : IDL.Null,
  'LeadCreated' : IDL.Null,
  'AiSummary' : IDL.Null,
  'EmailSent' : IDL.Null,
  'TaskCreated' : IDL.Null,
  'LeadUpdated' : IDL.Null,
  'StatusChange' : IDL.Null,
  'Called' : IDL.Null,
  'NoteAdded' : IDL.Null,
});
export const ActivityEntry = IDL.Record({
  'id' : ActivityId,
  'activityType' : ActivityType,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'leadId' : LeadId,
});
export const Role = IDL.Variant({
  'SalesManager' : IDL.Null,
  'Counselor' : IDL.Null,
  'Telecaller' : IDL.Null,
  'Admin' : IDL.Null,
});
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : Role,
  'email' : IDL.Text,
  'avatar' : IDL.Text,
});

export const idlService = IDL.Service({
  'addDocument' : IDL.Func(
      [LeadId, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [Document],
      [],
    ),
  'assignLead' : IDL.Func([LeadId, IDL.Opt(UserId)], [LeadPublic], []),
  'completeFollowUpTask' : IDL.Func([TaskId], [FollowUpTaskPublic], []),
  'createFollowUpTask' : IDL.Func([CreateTaskInput], [FollowUpTaskPublic], []),
  'createLead' : IDL.Func([CreateLeadInput], [LeadPublic], []),
  'deleteDocument' : IDL.Func([DocumentId], [IDL.Bool], []),
  'deleteFollowUpTask' : IDL.Func([TaskId], [IDL.Bool], []),
  'deleteLead' : IDL.Func([LeadId], [IDL.Bool], []),
  'filterLeads' : IDL.Func([LeadFilter], [IDL.Vec(LeadPublic)], ['query']),
  'generateSampleData' : IDL.Func([], [IDL.Nat], []),
  'getConversionFunnel' : IDL.Func([], [IDL.Vec(FunnelStage)], ['query']),
  'getCounselorStats' : IDL.Func([], [IDL.Vec(CounselorStats)], ['query']),
  'getDashboardStats' : IDL.Func([], [LeadStats], ['query']),
  'getDocumentsByLead' : IDL.Func([LeadId], [IDL.Vec(Document)], ['query']),
  'getFollowUpTask' : IDL.Func(
      [TaskId],
      [IDL.Opt(FollowUpTaskPublic)],
      ['query'],
    ),
  'getLead' : IDL.Func([LeadId], [IDL.Opt(LeadPublic)], ['query']),
  'getLeadTimeline' : IDL.Func([LeadId], [IDL.Vec(ActivityEntry)], ['query']),
  'getLeadsBySourceCounts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(LeadSource, IDL.Nat))],
      ['query'],
    ),
  'getLeadsByStatus' : IDL.Func([LeadStatus], [IDL.Vec(LeadPublic)], ['query']),
  'getLeadsByStatusCounts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(LeadStatus, IDL.Nat))],
      ['query'],
    ),
  'getLeadsCreatedInPeriod' : IDL.Func(
      [Timestamp, Timestamp],
      [IDL.Nat],
      ['query'],
    ),
  'getMyActivities' : IDL.Func([], [IDL.Vec(ActivityEntry)], ['query']),
  'getMyLeads' : IDL.Func([], [IDL.Vec(LeadPublic)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], []),
  'getMyTasks' : IDL.Func([], [IDL.Vec(FollowUpTaskPublic)], ['query']),
  'getOverdueTasks' : IDL.Func([], [IDL.Vec(FollowUpTaskPublic)], ['query']),
  'getRecentActivities' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ActivityEntry)],
      ['query'],
    ),
  'getTasksByLead' : IDL.Func(
      [LeadId],
      [IDL.Vec(FollowUpTaskPublic)],
      ['query'],
    ),
  'getTotalLeads' : IDL.Func([], [IDL.Nat], ['query']),
  'importLeads' : IDL.Func([IDL.Vec(CreateLeadInput)], [IDL.Nat], []),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfilePublic)], ['query']),
  'listLeads' : IDL.Func([], [IDL.Vec(LeadPublic)], ['query']),
  'registerProfile' : IDL.Func(
      [IDL.Text, IDL.Text, Role, IDL.Text],
      [UserProfilePublic],
      [],
    ),
  'setMyAiApiKey' : IDL.Func([IDL.Text], [], []),
  'setUserRole' : IDL.Func([UserId, Role], [UserProfilePublic], []),
  'updateLead' : IDL.Func([LeadId, CreateLeadInput], [LeadPublic], []),
  'updateLeadNotes' : IDL.Func([LeadId, IDL.Text], [LeadPublic], []),
  'updateLeadStatus' : IDL.Func([LeadId, LeadStatus], [LeadPublic], []),
  'updateLeadTags' : IDL.Func([LeadId, IDL.Vec(IDL.Text)], [LeadPublic], []),
  'updateMyProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [UserProfilePublic],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LeadId = IDL.Nat;
  const DocumentId = IDL.Nat;
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const Document = IDL.Record({
    'id' : DocumentId,
    'fileSize' : IDL.Nat,
    'fileType' : IDL.Text,
    'filename' : IDL.Text,
    'leadId' : LeadId,
    'storageUrl' : IDL.Text,
    'uploadedAt' : Timestamp,
    'uploadedBy' : UserId,
  });
  const LeadStatus = IDL.Variant({
    'Won' : IDL.Null,
    'Lost' : IDL.Null,
    'ProposalSent' : IDL.Null,
    'Contacted' : IDL.Null,
    'Qualified' : IDL.Null,
    'FollowUpScheduled' : IDL.Null,
    'NewLead' : IDL.Null,
    'Interested' : IDL.Null,
    'NotInterested' : IDL.Null,
  });
  const LeadSource = IDL.Variant({
    'Website' : IDL.Null,
    'ManualEntry' : IDL.Null,
    'LandingPage' : IDL.Null,
    'FacebookAds' : IDL.Null,
    'Other' : IDL.Text,
    'CsvUpload' : IDL.Null,
    'ApiIntegration' : IDL.Null,
    'Referral' : IDL.Null,
    'GoogleAds' : IDL.Null,
  });
  const StatusHistoryEntry = IDL.Record({
    'status' : LeadStatus,
    'changedAt' : Timestamp,
    'changedBy' : UserId,
  });
  const LeadPublic = IDL.Record({
    'id' : LeadId,
    'status' : LeadStatus,
    'source' : LeadSource,
    'campaign' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'statusHistory' : IDL.Vec(StatusHistoryEntry),
    'email' : IDL.Text,
    'updatedAt' : Timestamp,
    'courseInterest' : IDL.Text,
    'notes' : IDL.Text,
    'dealValue' : IDL.Nat,
    'phone' : IDL.Text,
    'assignedUserId' : IDL.Opt(UserId),
  });
  const TaskId = IDL.Nat;
  const RecurringType = IDL.Variant({
    'Weekly' : IDL.Null,
    'None' : IDL.Null,
    'Daily' : IDL.Null,
    'Monthly' : IDL.Null,
  });
  const TaskStatus = IDL.Variant({
    'Overdue' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const TaskType = IDL.Variant({
    'Sms' : IDL.Null,
    'Email' : IDL.Null,
    'Call' : IDL.Null,
    'Whatsapp' : IDL.Null,
    'Meeting' : IDL.Null,
  });
  const FollowUpTaskPublic = IDL.Record({
    'id' : TaskId,
    'title' : IDL.Text,
    'assignedTo' : UserId,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'recurring' : RecurringType,
    'dueDate' : Timestamp,
    'taskStatus' : TaskStatus,
    'taskType' : TaskType,
    'leadId' : LeadId,
    'nextRunDate' : IDL.Opt(Timestamp),
  });
  const CreateTaskInput = IDL.Record({
    'title' : IDL.Text,
    'assignedTo' : UserId,
    'recurring' : RecurringType,
    'dueDate' : Timestamp,
    'taskType' : TaskType,
    'leadId' : LeadId,
  });
  const CreateLeadInput = IDL.Record({
    'source' : LeadSource,
    'campaign' : IDL.Text,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'email' : IDL.Text,
    'courseInterest' : IDL.Text,
    'notes' : IDL.Text,
    'dealValue' : IDL.Nat,
    'phone' : IDL.Text,
    'assignedUserId' : IDL.Opt(UserId),
  });
  const LeadFilter = IDL.Record({
    'tag' : IDL.Opt(IDL.Text),
    'status' : IDL.Opt(LeadStatus),
    'source' : IDL.Opt(LeadSource),
    'campaign' : IDL.Opt(IDL.Text),
    'toDate' : IDL.Opt(Timestamp),
    'fromDate' : IDL.Opt(Timestamp),
    'assignedUserId' : IDL.Opt(UserId),
  });
  const FunnelStage = IDL.Record({ 'status' : LeadStatus, 'count' : IDL.Nat });
  const CounselorStats = IDL.Record({
    'userId' : UserId,
    'totalAssigned' : IDL.Nat,
    'totalFollowedUp' : IDL.Nat,
    'totalConverted' : IDL.Nat,
  });
  const LeadStats = IDL.Record({
    'totalLeads' : IDL.Nat,
    'totalDealValue' : IDL.Nat,
    'wonLeads' : IDL.Nat,
    'conversionRate' : IDL.Nat,
    'byStatus' : IDL.Vec(IDL.Tuple(LeadStatus, IDL.Nat)),
    'bySource' : IDL.Vec(IDL.Tuple(LeadSource, IDL.Nat)),
  });
  const ActivityId = IDL.Nat;
  const ActivityType = IDL.Variant({
    'TaskCompleted' : IDL.Null,
    'WhatsappSent' : IDL.Null,
    'DocumentUploaded' : IDL.Null,
    'LeadCreated' : IDL.Null,
    'AiSummary' : IDL.Null,
    'EmailSent' : IDL.Null,
    'TaskCreated' : IDL.Null,
    'LeadUpdated' : IDL.Null,
    'StatusChange' : IDL.Null,
    'Called' : IDL.Null,
    'NoteAdded' : IDL.Null,
  });
  const ActivityEntry = IDL.Record({
    'id' : ActivityId,
    'activityType' : ActivityType,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'leadId' : LeadId,
  });
  const Role = IDL.Variant({
    'SalesManager' : IDL.Null,
    'Counselor' : IDL.Null,
    'Telecaller' : IDL.Null,
    'Admin' : IDL.Null,
  });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : Role,
    'email' : IDL.Text,
    'avatar' : IDL.Text,
  });
  
  return IDL.Service({
    'addDocument' : IDL.Func(
        [LeadId, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [Document],
        [],
      ),
    'assignLead' : IDL.Func([LeadId, IDL.Opt(UserId)], [LeadPublic], []),
    'completeFollowUpTask' : IDL.Func([TaskId], [FollowUpTaskPublic], []),
    'createFollowUpTask' : IDL.Func(
        [CreateTaskInput],
        [FollowUpTaskPublic],
        [],
      ),
    'createLead' : IDL.Func([CreateLeadInput], [LeadPublic], []),
    'deleteDocument' : IDL.Func([DocumentId], [IDL.Bool], []),
    'deleteFollowUpTask' : IDL.Func([TaskId], [IDL.Bool], []),
    'deleteLead' : IDL.Func([LeadId], [IDL.Bool], []),
    'filterLeads' : IDL.Func([LeadFilter], [IDL.Vec(LeadPublic)], ['query']),
    'generateSampleData' : IDL.Func([], [IDL.Nat], []),
    'getConversionFunnel' : IDL.Func([], [IDL.Vec(FunnelStage)], ['query']),
    'getCounselorStats' : IDL.Func([], [IDL.Vec(CounselorStats)], ['query']),
    'getDashboardStats' : IDL.Func([], [LeadStats], ['query']),
    'getDocumentsByLead' : IDL.Func([LeadId], [IDL.Vec(Document)], ['query']),
    'getFollowUpTask' : IDL.Func(
        [TaskId],
        [IDL.Opt(FollowUpTaskPublic)],
        ['query'],
      ),
    'getLead' : IDL.Func([LeadId], [IDL.Opt(LeadPublic)], ['query']),
    'getLeadTimeline' : IDL.Func([LeadId], [IDL.Vec(ActivityEntry)], ['query']),
    'getLeadsBySourceCounts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(LeadSource, IDL.Nat))],
        ['query'],
      ),
    'getLeadsByStatus' : IDL.Func(
        [LeadStatus],
        [IDL.Vec(LeadPublic)],
        ['query'],
      ),
    'getLeadsByStatusCounts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(LeadStatus, IDL.Nat))],
        ['query'],
      ),
    'getLeadsCreatedInPeriod' : IDL.Func(
        [Timestamp, Timestamp],
        [IDL.Nat],
        ['query'],
      ),
    'getMyActivities' : IDL.Func([], [IDL.Vec(ActivityEntry)], ['query']),
    'getMyLeads' : IDL.Func([], [IDL.Vec(LeadPublic)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], []),
    'getMyTasks' : IDL.Func([], [IDL.Vec(FollowUpTaskPublic)], ['query']),
    'getOverdueTasks' : IDL.Func([], [IDL.Vec(FollowUpTaskPublic)], ['query']),
    'getRecentActivities' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ActivityEntry)],
        ['query'],
      ),
    'getTasksByLead' : IDL.Func(
        [LeadId],
        [IDL.Vec(FollowUpTaskPublic)],
        ['query'],
      ),
    'getTotalLeads' : IDL.Func([], [IDL.Nat], ['query']),
    'importLeads' : IDL.Func([IDL.Vec(CreateLeadInput)], [IDL.Nat], []),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfilePublic)], ['query']),
    'listLeads' : IDL.Func([], [IDL.Vec(LeadPublic)], ['query']),
    'registerProfile' : IDL.Func(
        [IDL.Text, IDL.Text, Role, IDL.Text],
        [UserProfilePublic],
        [],
      ),
    'setMyAiApiKey' : IDL.Func([IDL.Text], [], []),
    'setUserRole' : IDL.Func([UserId, Role], [UserProfilePublic], []),
    'updateLead' : IDL.Func([LeadId, CreateLeadInput], [LeadPublic], []),
    'updateLeadNotes' : IDL.Func([LeadId, IDL.Text], [LeadPublic], []),
    'updateLeadStatus' : IDL.Func([LeadId, LeadStatus], [LeadPublic], []),
    'updateLeadTags' : IDL.Func([LeadId, IDL.Vec(IDL.Text)], [LeadPublic], []),
    'updateMyProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [UserProfilePublic],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };