/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityEntry {
  'id' : ActivityId,
  'activityType' : ActivityType,
  'content' : string,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'leadId' : LeadId,
}
export type ActivityId = bigint;
export type ActivityType = { 'TaskCompleted' : null } |
  { 'WhatsappSent' : null } |
  { 'DocumentUploaded' : null } |
  { 'LeadCreated' : null } |
  { 'AiSummary' : null } |
  { 'EmailSent' : null } |
  { 'TaskCreated' : null } |
  { 'LeadUpdated' : null } |
  { 'StatusChange' : null } |
  { 'Called' : null } |
  { 'NoteAdded' : null };
export interface CounselorStats {
  'userId' : UserId,
  'totalAssigned' : bigint,
  'totalFollowedUp' : bigint,
  'totalConverted' : bigint,
}
export interface CreateLeadInput {
  'source' : LeadSource,
  'campaign' : string,
  'name' : string,
  'tags' : Array<string>,
  'email' : string,
  'courseInterest' : string,
  'notes' : string,
  'dealValue' : bigint,
  'phone' : string,
  'assignedUserId' : [] | [UserId],
}
export interface CreateTaskInput {
  'title' : string,
  'assignedTo' : UserId,
  'recurring' : RecurringType,
  'dueDate' : Timestamp,
  'taskType' : TaskType,
  'leadId' : LeadId,
}
export interface Document {
  'id' : DocumentId,
  'fileSize' : bigint,
  'fileType' : string,
  'filename' : string,
  'leadId' : LeadId,
  'storageUrl' : string,
  'uploadedAt' : Timestamp,
  'uploadedBy' : UserId,
}
export type DocumentId = bigint;
export interface FollowUpTaskPublic {
  'id' : TaskId,
  'title' : string,
  'assignedTo' : UserId,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'recurring' : RecurringType,
  'dueDate' : Timestamp,
  'taskStatus' : TaskStatus,
  'taskType' : TaskType,
  'leadId' : LeadId,
  'nextRunDate' : [] | [Timestamp],
}
export interface FunnelStage { 'status' : LeadStatus, 'count' : bigint }
export interface LeadFilter {
  'tag' : [] | [string],
  'status' : [] | [LeadStatus],
  'source' : [] | [LeadSource],
  'campaign' : [] | [string],
  'toDate' : [] | [Timestamp],
  'fromDate' : [] | [Timestamp],
  'assignedUserId' : [] | [UserId],
}
export type LeadId = bigint;
export interface LeadPublic {
  'id' : LeadId,
  'status' : LeadStatus,
  'source' : LeadSource,
  'campaign' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'statusHistory' : Array<StatusHistoryEntry>,
  'email' : string,
  'updatedAt' : Timestamp,
  'courseInterest' : string,
  'notes' : string,
  'dealValue' : bigint,
  'phone' : string,
  'assignedUserId' : [] | [UserId],
}
export type LeadSource = { 'Website' : null } |
  { 'ManualEntry' : null } |
  { 'LandingPage' : null } |
  { 'FacebookAds' : null } |
  { 'Other' : string } |
  { 'CsvUpload' : null } |
  { 'ApiIntegration' : null } |
  { 'Referral' : null } |
  { 'GoogleAds' : null };
export interface LeadStats {
  'totalLeads' : bigint,
  'totalDealValue' : bigint,
  'wonLeads' : bigint,
  'conversionRate' : bigint,
  'byStatus' : Array<[LeadStatus, bigint]>,
  'bySource' : Array<[LeadSource, bigint]>,
}
export type LeadStatus = { 'Won' : null } |
  { 'Lost' : null } |
  { 'ProposalSent' : null } |
  { 'Contacted' : null } |
  { 'Qualified' : null } |
  { 'FollowUpScheduled' : null } |
  { 'NewLead' : null } |
  { 'Interested' : null } |
  { 'NotInterested' : null };
export type RecurringType = { 'Weekly' : null } |
  { 'None' : null } |
  { 'Daily' : null } |
  { 'Monthly' : null };
export type Role = { 'SalesManager' : null } |
  { 'Counselor' : null } |
  { 'Telecaller' : null } |
  { 'Admin' : null };
export interface StatusHistoryEntry {
  'status' : LeadStatus,
  'changedAt' : Timestamp,
  'changedBy' : UserId,
}
export type TaskId = bigint;
export type TaskStatus = { 'Overdue' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export type TaskType = { 'Sms' : null } |
  { 'Email' : null } |
  { 'Call' : null } |
  { 'Whatsapp' : null } |
  { 'Meeting' : null };
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : Role,
  'email' : string,
  'avatar' : string,
}
export interface _SERVICE {
  'addDocument' : ActorMethod<
    [LeadId, string, string, string, bigint],
    Document
  >,
  'assignLead' : ActorMethod<[LeadId, [] | [UserId]], LeadPublic>,
  'completeFollowUpTask' : ActorMethod<[TaskId], FollowUpTaskPublic>,
  'createFollowUpTask' : ActorMethod<[CreateTaskInput], FollowUpTaskPublic>,
  'createLead' : ActorMethod<[CreateLeadInput], LeadPublic>,
  'deleteDocument' : ActorMethod<[DocumentId], boolean>,
  'deleteFollowUpTask' : ActorMethod<[TaskId], boolean>,
  'deleteLead' : ActorMethod<[LeadId], boolean>,
  'filterLeads' : ActorMethod<[LeadFilter], Array<LeadPublic>>,
  'generateSampleData' : ActorMethod<[], bigint>,
  'getConversionFunnel' : ActorMethod<[], Array<FunnelStage>>,
  'getCounselorStats' : ActorMethod<[], Array<CounselorStats>>,
  'getDashboardStats' : ActorMethod<[], LeadStats>,
  'getDocumentsByLead' : ActorMethod<[LeadId], Array<Document>>,
  'getFollowUpTask' : ActorMethod<[TaskId], [] | [FollowUpTaskPublic]>,
  'getLead' : ActorMethod<[LeadId], [] | [LeadPublic]>,
  'getLeadTimeline' : ActorMethod<[LeadId], Array<ActivityEntry>>,
  'getLeadsBySourceCounts' : ActorMethod<[], Array<[LeadSource, bigint]>>,
  'getLeadsByStatus' : ActorMethod<[LeadStatus], Array<LeadPublic>>,
  'getLeadsByStatusCounts' : ActorMethod<[], Array<[LeadStatus, bigint]>>,
  'getLeadsCreatedInPeriod' : ActorMethod<[Timestamp, Timestamp], bigint>,
  'getMyActivities' : ActorMethod<[], Array<ActivityEntry>>,
  'getMyLeads' : ActorMethod<[], Array<LeadPublic>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getMyTasks' : ActorMethod<[], Array<FollowUpTaskPublic>>,
  'getOverdueTasks' : ActorMethod<[], Array<FollowUpTaskPublic>>,
  'getRecentActivities' : ActorMethod<[bigint], Array<ActivityEntry>>,
  'getTasksByLead' : ActorMethod<[LeadId], Array<FollowUpTaskPublic>>,
  'getTotalLeads' : ActorMethod<[], bigint>,
  'importLeads' : ActorMethod<[Array<CreateLeadInput>], bigint>,
  'listAllUsers' : ActorMethod<[], Array<UserProfilePublic>>,
  'listLeads' : ActorMethod<[], Array<LeadPublic>>,
  'registerProfile' : ActorMethod<
    [string, string, Role, string],
    UserProfilePublic
  >,
  'setMyAiApiKey' : ActorMethod<[string], undefined>,
  'setUserRole' : ActorMethod<[UserId, Role], UserProfilePublic>,
  'updateLead' : ActorMethod<[LeadId, CreateLeadInput], LeadPublic>,
  'updateLeadNotes' : ActorMethod<[LeadId, string], LeadPublic>,
  'updateLeadStatus' : ActorMethod<[LeadId, LeadStatus], LeadPublic>,
  'updateLeadTags' : ActorMethod<[LeadId, Array<string>], LeadPublic>,
  'updateMyProfile' : ActorMethod<[string, string, string], UserProfilePublic>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];