/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type LeadId = bigint;
export interface CreateLeadInput {
    source: LeadSource;
    campaign: string;
    name: string;
    tags: Array<string>;
    email: string;
    courseInterest: string;
    notes: string;
    dealValue: bigint;
    phone: string;
    assignedUserId?: UserId;
}
export interface LeadPublic {
    id: LeadId;
    status: LeadStatus;
    source: LeadSource;
    campaign: string;
    name: string;
    createdAt: Timestamp;
    tags: Array<string>;
    statusHistory: Array<StatusHistoryEntry>;
    email: string;
    updatedAt: Timestamp;
    courseInterest: string;
    notes: string;
    dealValue: bigint;
    phone: string;
    assignedUserId?: UserId;
}
export interface FollowUpTaskPublic {
    id: TaskId;
    title: string;
    assignedTo: UserId;
    createdAt: Timestamp;
    createdBy: UserId;
    recurring: RecurringType;
    dueDate: Timestamp;
    taskStatus: TaskStatus;
    taskType: TaskType;
    leadId: LeadId;
    nextRunDate?: Timestamp;
}
export interface Document {
    id: DocumentId;
    fileSize: bigint;
    fileType: string;
    filename: string;
    leadId: LeadId;
    storageUrl: string;
    uploadedAt: Timestamp;
    uploadedBy: UserId;
}
export interface FunnelStage {
    status: LeadStatus;
    count: bigint;
}
export type LeadSource = {
    __kind__: "Website";
    Website: null;
} | {
    __kind__: "ManualEntry";
    ManualEntry: null;
} | {
    __kind__: "LandingPage";
    LandingPage: null;
} | {
    __kind__: "FacebookAds";
    FacebookAds: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "CsvUpload";
    CsvUpload: null;
} | {
    __kind__: "ApiIntegration";
    ApiIntegration: null;
} | {
    __kind__: "Referral";
    Referral: null;
} | {
    __kind__: "GoogleAds";
    GoogleAds: null;
};
export interface CreateTaskInput {
    title: string;
    assignedTo: UserId;
    recurring: RecurringType;
    dueDate: Timestamp;
    taskType: TaskType;
    leadId: LeadId;
}
export interface LeadFilter {
    tag?: string;
    status?: LeadStatus;
    source?: LeadSource;
    campaign?: string;
    toDate?: Timestamp;
    fromDate?: Timestamp;
    assignedUserId?: UserId;
}
export interface UserProfilePublic {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: Role;
    email: string;
    avatar: string;
}
export interface StatusHistoryEntry {
    status: LeadStatus;
    changedAt: Timestamp;
    changedBy: UserId;
}
export type UserId = Principal;
export interface LeadStats {
    totalLeads: bigint;
    totalDealValue: bigint;
    wonLeads: bigint;
    conversionRate: bigint;
    byStatus: Array<[LeadStatus, bigint]>;
    bySource: Array<[LeadSource, bigint]>;
}
export type ActivityId = bigint;
export type TaskId = bigint;
export type DocumentId = bigint;
export interface CounselorStats {
    userId: UserId;
    totalAssigned: bigint;
    totalFollowedUp: bigint;
    totalConverted: bigint;
}
export interface ActivityEntry {
    id: ActivityId;
    activityType: ActivityType;
    content: string;
    createdAt: Timestamp;
    createdBy: UserId;
    leadId: LeadId;
}
export enum ActivityType {
    TaskCompleted = "TaskCompleted",
    WhatsappSent = "WhatsappSent",
    DocumentUploaded = "DocumentUploaded",
    LeadCreated = "LeadCreated",
    AiSummary = "AiSummary",
    EmailSent = "EmailSent",
    TaskCreated = "TaskCreated",
    LeadUpdated = "LeadUpdated",
    StatusChange = "StatusChange",
    Called = "Called",
    NoteAdded = "NoteAdded"
}
export enum LeadStatus {
    Won = "Won",
    Lost = "Lost",
    ProposalSent = "ProposalSent",
    Contacted = "Contacted",
    Qualified = "Qualified",
    FollowUpScheduled = "FollowUpScheduled",
    NewLead = "NewLead",
    Interested = "Interested",
    NotInterested = "NotInterested"
}
export enum RecurringType {
    Weekly = "Weekly",
    None = "None",
    Daily = "Daily",
    Monthly = "Monthly"
}
export enum Role {
    SalesManager = "SalesManager",
    Counselor = "Counselor",
    Telecaller = "Telecaller",
    Admin = "Admin"
}
export enum TaskStatus {
    Overdue = "Overdue",
    Completed = "Completed",
    Pending = "Pending"
}
export enum TaskType {
    Sms = "Sms",
    Email = "Email",
    Call = "Call",
    Whatsapp = "Whatsapp",
    Meeting = "Meeting"
}
export interface backendInterface {
    addDocument(leadId: LeadId, filename: string, storageUrl: string, fileType: string, fileSize: bigint): Promise<Document>;
    assignLead(id: LeadId, assignedUserId: UserId | null): Promise<LeadPublic>;
    completeFollowUpTask(id: TaskId): Promise<FollowUpTaskPublic>;
    createFollowUpTask(input: CreateTaskInput): Promise<FollowUpTaskPublic>;
    createLead(input: CreateLeadInput): Promise<LeadPublic>;
    deleteDocument(id: DocumentId): Promise<boolean>;
    deleteFollowUpTask(id: TaskId): Promise<boolean>;
    deleteLead(id: LeadId): Promise<boolean>;
    filterLeads(filter: LeadFilter): Promise<Array<LeadPublic>>;
    generateSampleData(): Promise<bigint>;
    getConversionFunnel(): Promise<Array<FunnelStage>>;
    getCounselorStats(): Promise<Array<CounselorStats>>;
    getDashboardStats(): Promise<LeadStats>;
    getDocumentsByLead(leadId: LeadId): Promise<Array<Document>>;
    getFollowUpTask(id: TaskId): Promise<FollowUpTaskPublic | null>;
    getLead(id: LeadId): Promise<LeadPublic | null>;
    getLeadTimeline(leadId: LeadId): Promise<Array<ActivityEntry>>;
    getLeadsBySourceCounts(): Promise<Array<[LeadSource, bigint]>>;
    getLeadsByStatus(status: LeadStatus): Promise<Array<LeadPublic>>;
    getLeadsByStatusCounts(): Promise<Array<[LeadStatus, bigint]>>;
    getLeadsCreatedInPeriod(fromDate: Timestamp, toDate: Timestamp): Promise<bigint>;
    getMyActivities(): Promise<Array<ActivityEntry>>;
    getMyLeads(): Promise<Array<LeadPublic>>;
    getMyProfile(): Promise<UserProfilePublic | null>;
    getMyTasks(): Promise<Array<FollowUpTaskPublic>>;
    getOverdueTasks(): Promise<Array<FollowUpTaskPublic>>;
    getRecentActivities(limit: bigint): Promise<Array<ActivityEntry>>;
    getTasksByLead(leadId: LeadId): Promise<Array<FollowUpTaskPublic>>;
    getTotalLeads(): Promise<bigint>;
    importLeads(inputs: Array<CreateLeadInput>): Promise<bigint>;
    listAllUsers(): Promise<Array<UserProfilePublic>>;
    listLeads(): Promise<Array<LeadPublic>>;
    registerProfile(name: string, email: string, role: Role, avatar: string): Promise<UserProfilePublic>;
    setMyAiApiKey(apiKey: string): Promise<void>;
    setUserRole(targetUser: UserId, role: Role): Promise<UserProfilePublic>;
    updateLead(id: LeadId, input: CreateLeadInput): Promise<LeadPublic>;
    updateLeadNotes(id: LeadId, notes: string): Promise<LeadPublic>;
    updateLeadStatus(id: LeadId, newStatus: LeadStatus): Promise<LeadPublic>;
    updateLeadTags(id: LeadId, tags: Array<string>): Promise<LeadPublic>;
    updateMyProfile(name: string, email: string, avatar: string): Promise<UserProfilePublic>;
}
import type { ActivityEntry as _ActivityEntry, ActivityId as _ActivityId, ActivityType as _ActivityType, CreateLeadInput as _CreateLeadInput, CreateTaskInput as _CreateTaskInput, FollowUpTaskPublic as _FollowUpTaskPublic, FunnelStage as _FunnelStage, LeadFilter as _LeadFilter, LeadId as _LeadId, LeadPublic as _LeadPublic, LeadSource as _LeadSource, LeadStats as _LeadStats, LeadStatus as _LeadStatus, RecurringType as _RecurringType, Role as _Role, StatusHistoryEntry as _StatusHistoryEntry, TaskId as _TaskId, TaskStatus as _TaskStatus, TaskType as _TaskType, Timestamp as _Timestamp, UserId as _UserId, UserProfilePublic as _UserProfilePublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addDocument(arg0: LeadId, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<Document> {
        if (this.processError) {
            try {
                const result = await this.actor.addDocument(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDocument(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async assignLead(arg0: LeadId, arg1: UserId | null): Promise<LeadPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.assignLead(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_LeadPublic_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignLead(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_LeadPublic_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async completeFollowUpTask(arg0: TaskId): Promise<FollowUpTaskPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.completeFollowUpTask(arg0);
                return from_candid_FollowUpTaskPublic_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeFollowUpTask(arg0);
            return from_candid_FollowUpTaskPublic_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createFollowUpTask(arg0: CreateTaskInput): Promise<FollowUpTaskPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createFollowUpTask(to_candid_CreateTaskInput_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_FollowUpTaskPublic_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFollowUpTask(to_candid_CreateTaskInput_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_FollowUpTaskPublic_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createLead(arg0: CreateLeadInput): Promise<LeadPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createLead(to_candid_CreateLeadInput_n27(this._uploadFile, this._downloadFile, arg0));
                return from_candid_LeadPublic_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLead(to_candid_CreateLeadInput_n27(this._uploadFile, this._downloadFile, arg0));
            return from_candid_LeadPublic_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDocument(arg0: DocumentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocument(arg0);
            return result;
        }
    }
    async deleteFollowUpTask(arg0: TaskId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFollowUpTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFollowUpTask(arg0);
            return result;
        }
    }
    async deleteLead(arg0: LeadId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLead(arg0);
            return result;
        }
    }
    async filterLeads(arg0: LeadFilter): Promise<Array<LeadPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterLeads(to_candid_LeadFilter_n31(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterLeads(to_candid_LeadFilter_n31(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateSampleData(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.generateSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateSampleData();
            return result;
        }
    }
    async getConversionFunnel(): Promise<Array<FunnelStage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversionFunnel();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversionFunnel();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCounselorStats(): Promise<Array<CounselorStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCounselorStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCounselorStats();
            return result;
        }
    }
    async getDashboardStats(): Promise<LeadStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return from_candid_LeadStats_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return from_candid_LeadStats_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocumentsByLead(arg0: LeadId): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentsByLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentsByLead(arg0);
            return result;
        }
    }
    async getFollowUpTask(arg0: TaskId): Promise<FollowUpTaskPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowUpTask(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowUpTask(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLead(arg0: LeadId): Promise<LeadPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLead(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLead(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadTimeline(arg0: LeadId): Promise<Array<ActivityEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadTimeline(arg0);
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadTimeline(arg0);
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadsBySourceCounts(): Promise<Array<[LeadSource, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsBySourceCounts();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsBySourceCounts();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadsByStatus(arg0: LeadStatus): Promise<Array<LeadPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsByStatus(to_candid_LeadStatus_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsByStatus(to_candid_LeadStatus_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadsByStatusCounts(): Promise<Array<[LeadStatus, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsByStatusCounts();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsByStatusCounts();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadsCreatedInPeriod(arg0: Timestamp, arg1: Timestamp): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsCreatedInPeriod(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsCreatedInPeriod(arg0, arg1);
            return result;
        }
    }
    async getMyActivities(): Promise<Array<ActivityEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyActivities();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyActivities();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyLeads(): Promise<Array<LeadPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLeads();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLeads();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTasks(): Promise<Array<FollowUpTaskPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTasks();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTasks();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOverdueTasks(): Promise<Array<FollowUpTaskPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOverdueTasks();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOverdueTasks();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentActivities(arg0: bigint): Promise<Array<ActivityEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentActivities(arg0);
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentActivities(arg0);
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByLead(arg0: LeadId): Promise<Array<FollowUpTaskPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByLead(arg0);
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByLead(arg0);
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalLeads(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalLeads();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalLeads();
            return result;
        }
    }
    async importLeads(arg0: Array<CreateLeadInput>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.importLeads(to_candid_vec_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importLeads(to_candid_vec_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async listAllUsers(): Promise<Array<UserProfilePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async listLeads(): Promise<Array<LeadPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLeads();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLeads();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerProfile(arg0: string, arg1: string, arg2: Role, arg3: string): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.registerProfile(arg0, arg1, to_candid_Role_n60(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_UserProfilePublic_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerProfile(arg0, arg1, to_candid_Role_n60(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_UserProfilePublic_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async setMyAiApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMyAiApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMyAiApiKey(arg0);
            return result;
        }
    }
    async setUserRole(arg0: UserId, arg1: Role): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserRole(arg0, to_candid_Role_n60(this._uploadFile, this._downloadFile, arg1));
                return from_candid_UserProfilePublic_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserRole(arg0, to_candid_Role_n60(this._uploadFile, this._downloadFile, arg1));
            return from_candid_UserProfilePublic_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLead(arg0: LeadId, arg1: CreateLeadInput): Promise<LeadPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLead(arg0, to_candid_CreateLeadInput_n27(this._uploadFile, this._downloadFile, arg1));
                return from_candid_LeadPublic_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLead(arg0, to_candid_CreateLeadInput_n27(this._uploadFile, this._downloadFile, arg1));
            return from_candid_LeadPublic_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLeadNotes(arg0: LeadId, arg1: string): Promise<LeadPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeadNotes(arg0, arg1);
                return from_candid_LeadPublic_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeadNotes(arg0, arg1);
            return from_candid_LeadPublic_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLeadStatus(arg0: LeadId, arg1: LeadStatus): Promise<LeadPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeadStatus(arg0, to_candid_LeadStatus_n33(this._uploadFile, this._downloadFile, arg1));
                return from_candid_LeadPublic_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeadStatus(arg0, to_candid_LeadStatus_n33(this._uploadFile, this._downloadFile, arg1));
            return from_candid_LeadPublic_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLeadTags(arg0: LeadId, arg1: Array<string>): Promise<LeadPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeadTags(arg0, arg1);
                return from_candid_LeadPublic_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeadTags(arg0, arg1);
            return from_candid_LeadPublic_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMyProfile(arg0: string, arg1: string, arg2: string): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(arg0, arg1, arg2);
                return from_candid_UserProfilePublic_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(arg0, arg1, arg2);
            return from_candid_UserProfilePublic_n53(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ActivityEntry_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityEntry): ActivityEntry {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_ActivityType_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityType): ActivityType {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_FollowUpTaskPublic_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FollowUpTaskPublic): FollowUpTaskPublic {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_FunnelStage_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FunnelStage): FunnelStage {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_LeadPublic_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadPublic): LeadPublic {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_LeadSource_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadSource): LeadSource {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_LeadStats_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadStats): LeadStats {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_LeadStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadStatus): LeadStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_RecurringType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecurringType): RecurringType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function from_candid_StatusHistoryEntry_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StatusHistoryEntry): StatusHistoryEntry {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_TaskType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskType): TaskType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FollowUpTaskPublic]): FollowUpTaskPublic | null {
    return value.length === 0 ? null : from_candid_FollowUpTaskPublic_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LeadPublic]): LeadPublic | null {
    return value.length === 0 ? null : from_candid_LeadPublic_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n53(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _LeadStatus;
    changedAt: _Timestamp;
    changedBy: _UserId;
}): {
    status: LeadStatus;
    changedAt: Timestamp;
    changedBy: UserId;
} {
    return {
        status: from_candid_LeadStatus_n4(_uploadFile, _downloadFile, value.status),
        changedAt: value.changedAt,
        changedBy: value.changedBy
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TaskId;
    title: string;
    assignedTo: _UserId;
    createdAt: _Timestamp;
    createdBy: _UserId;
    recurring: _RecurringType;
    dueDate: _Timestamp;
    taskStatus: _TaskStatus;
    taskType: _TaskType;
    leadId: _LeadId;
    nextRunDate: [] | [_Timestamp];
}): {
    id: TaskId;
    title: string;
    assignedTo: UserId;
    createdAt: Timestamp;
    createdBy: UserId;
    recurring: RecurringType;
    dueDate: Timestamp;
    taskStatus: TaskStatus;
    taskType: TaskType;
    leadId: LeadId;
    nextRunDate?: Timestamp;
} {
    return {
        id: value.id,
        title: value.title,
        assignedTo: value.assignedTo,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        recurring: from_candid_RecurringType_n14(_uploadFile, _downloadFile, value.recurring),
        dueDate: value.dueDate,
        taskStatus: from_candid_TaskStatus_n16(_uploadFile, _downloadFile, value.taskStatus),
        taskType: from_candid_TaskType_n18(_uploadFile, _downloadFile, value.taskType),
        leadId: value.leadId,
        nextRunDate: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.nextRunDate))
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LeadId;
    status: _LeadStatus;
    source: _LeadSource;
    campaign: string;
    name: string;
    createdAt: _Timestamp;
    tags: Array<string>;
    statusHistory: Array<_StatusHistoryEntry>;
    email: string;
    updatedAt: _Timestamp;
    courseInterest: string;
    notes: string;
    dealValue: bigint;
    phone: string;
    assignedUserId: [] | [_UserId];
}): {
    id: LeadId;
    status: LeadStatus;
    source: LeadSource;
    campaign: string;
    name: string;
    createdAt: Timestamp;
    tags: Array<string>;
    statusHistory: Array<StatusHistoryEntry>;
    email: string;
    updatedAt: Timestamp;
    courseInterest: string;
    notes: string;
    dealValue: bigint;
    phone: string;
    assignedUserId?: UserId;
} {
    return {
        id: value.id,
        status: from_candid_LeadStatus_n4(_uploadFile, _downloadFile, value.status),
        source: from_candid_LeadSource_n6(_uploadFile, _downloadFile, value.source),
        campaign: value.campaign,
        name: value.name,
        createdAt: value.createdAt,
        tags: value.tags,
        statusHistory: from_candid_vec_n8(_uploadFile, _downloadFile, value.statusHistory),
        email: value.email,
        updatedAt: value.updatedAt,
        courseInterest: value.courseInterest,
        notes: value.notes,
        dealValue: value.dealValue,
        phone: value.phone,
        assignedUserId: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.assignedUserId))
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _LeadStatus;
    count: bigint;
}): {
    status: LeadStatus;
    count: bigint;
} {
    return {
        status: from_candid_LeadStatus_n4(_uploadFile, _downloadFile, value.status),
        count: value.count
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalLeads: bigint;
    totalDealValue: bigint;
    wonLeads: bigint;
    conversionRate: bigint;
    byStatus: Array<[_LeadStatus, bigint]>;
    bySource: Array<[_LeadSource, bigint]>;
}): {
    totalLeads: bigint;
    totalDealValue: bigint;
    wonLeads: bigint;
    conversionRate: bigint;
    byStatus: Array<[LeadStatus, bigint]>;
    bySource: Array<[LeadSource, bigint]>;
} {
    return {
        totalLeads: value.totalLeads,
        totalDealValue: value.totalDealValue,
        wonLeads: value.wonLeads,
        conversionRate: value.conversionRate,
        byStatus: from_candid_vec_n41(_uploadFile, _downloadFile, value.byStatus),
        bySource: from_candid_vec_n43(_uploadFile, _downloadFile, value.bySource)
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ActivityId;
    activityType: _ActivityType;
    content: string;
    createdAt: _Timestamp;
    createdBy: _UserId;
    leadId: _LeadId;
}): {
    id: ActivityId;
    activityType: ActivityType;
    content: string;
    createdAt: Timestamp;
    createdBy: UserId;
    leadId: LeadId;
} {
    return {
        id: value.id,
        activityType: from_candid_ActivityType_n50(_uploadFile, _downloadFile, value.activityType),
        content: value.content,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        leadId: value.leadId
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    name: string;
    createdAt: _Timestamp;
    role: _Role;
    email: string;
    avatar: string;
}): {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: Role;
    email: string;
    avatar: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n55(_uploadFile, _downloadFile, value.role),
        email: value.email,
        avatar: value.avatar
    };
}
function from_candid_tuple_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_LeadStatus, bigint]): [LeadStatus, bigint] {
    return [
        from_candid_LeadStatus_n4(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_tuple_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_LeadSource, bigint]): [LeadSource, bigint] {
    return [
        from_candid_LeadSource_n6(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Weekly: null;
} | {
    None: null;
} | {
    Daily: null;
} | {
    Monthly: null;
}): RecurringType {
    return "Weekly" in value ? RecurringType.Weekly : "None" in value ? RecurringType.None : "Daily" in value ? RecurringType.Daily : "Monthly" in value ? RecurringType.Monthly : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Overdue: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): TaskStatus {
    return "Overdue" in value ? TaskStatus.Overdue : "Completed" in value ? TaskStatus.Completed : "Pending" in value ? TaskStatus.Pending : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Sms: null;
} | {
    Email: null;
} | {
    Call: null;
} | {
    Whatsapp: null;
} | {
    Meeting: null;
}): TaskType {
    return "Sms" in value ? TaskType.Sms : "Email" in value ? TaskType.Email : "Call" in value ? TaskType.Call : "Whatsapp" in value ? TaskType.Whatsapp : "Meeting" in value ? TaskType.Meeting : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Won: null;
} | {
    Lost: null;
} | {
    ProposalSent: null;
} | {
    Contacted: null;
} | {
    Qualified: null;
} | {
    FollowUpScheduled: null;
} | {
    NewLead: null;
} | {
    Interested: null;
} | {
    NotInterested: null;
}): LeadStatus {
    return "Won" in value ? LeadStatus.Won : "Lost" in value ? LeadStatus.Lost : "ProposalSent" in value ? LeadStatus.ProposalSent : "Contacted" in value ? LeadStatus.Contacted : "Qualified" in value ? LeadStatus.Qualified : "FollowUpScheduled" in value ? LeadStatus.FollowUpScheduled : "NewLead" in value ? LeadStatus.NewLead : "Interested" in value ? LeadStatus.Interested : "NotInterested" in value ? LeadStatus.NotInterested : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    TaskCompleted: null;
} | {
    WhatsappSent: null;
} | {
    DocumentUploaded: null;
} | {
    LeadCreated: null;
} | {
    AiSummary: null;
} | {
    EmailSent: null;
} | {
    TaskCreated: null;
} | {
    LeadUpdated: null;
} | {
    StatusChange: null;
} | {
    Called: null;
} | {
    NoteAdded: null;
}): ActivityType {
    return "TaskCompleted" in value ? ActivityType.TaskCompleted : "WhatsappSent" in value ? ActivityType.WhatsappSent : "DocumentUploaded" in value ? ActivityType.DocumentUploaded : "LeadCreated" in value ? ActivityType.LeadCreated : "AiSummary" in value ? ActivityType.AiSummary : "EmailSent" in value ? ActivityType.EmailSent : "TaskCreated" in value ? ActivityType.TaskCreated : "LeadUpdated" in value ? ActivityType.LeadUpdated : "StatusChange" in value ? ActivityType.StatusChange : "Called" in value ? ActivityType.Called : "NoteAdded" in value ? ActivityType.NoteAdded : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    SalesManager: null;
} | {
    Counselor: null;
} | {
    Telecaller: null;
} | {
    Admin: null;
}): Role {
    return "SalesManager" in value ? Role.SalesManager : "Counselor" in value ? Role.Counselor : "Telecaller" in value ? Role.Telecaller : "Admin" in value ? Role.Admin : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Website: null;
} | {
    ManualEntry: null;
} | {
    LandingPage: null;
} | {
    FacebookAds: null;
} | {
    Other: string;
} | {
    CsvUpload: null;
} | {
    ApiIntegration: null;
} | {
    Referral: null;
} | {
    GoogleAds: null;
}): {
    __kind__: "Website";
    Website: null;
} | {
    __kind__: "ManualEntry";
    ManualEntry: null;
} | {
    __kind__: "LandingPage";
    LandingPage: null;
} | {
    __kind__: "FacebookAds";
    FacebookAds: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "CsvUpload";
    CsvUpload: null;
} | {
    __kind__: "ApiIntegration";
    ApiIntegration: null;
} | {
    __kind__: "Referral";
    Referral: null;
} | {
    __kind__: "GoogleAds";
    GoogleAds: null;
} {
    return "Website" in value ? {
        __kind__: "Website",
        Website: value.Website
    } : "ManualEntry" in value ? {
        __kind__: "ManualEntry",
        ManualEntry: value.ManualEntry
    } : "LandingPage" in value ? {
        __kind__: "LandingPage",
        LandingPage: value.LandingPage
    } : "FacebookAds" in value ? {
        __kind__: "FacebookAds",
        FacebookAds: value.FacebookAds
    } : "Other" in value ? {
        __kind__: "Other",
        Other: value.Other
    } : "CsvUpload" in value ? {
        __kind__: "CsvUpload",
        CsvUpload: value.CsvUpload
    } : "ApiIntegration" in value ? {
        __kind__: "ApiIntegration",
        ApiIntegration: value.ApiIntegration
    } : "Referral" in value ? {
        __kind__: "Referral",
        Referral: value.Referral
    } : "GoogleAds" in value ? {
        __kind__: "GoogleAds",
        GoogleAds: value.GoogleAds
    } : value;
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeadPublic>): Array<LeadPublic> {
    return value.map((x)=>from_candid_LeadPublic_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FunnelStage>): Array<FunnelStage> {
    return value.map((x)=>from_candid_FunnelStage_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_LeadStatus, bigint]>): Array<[LeadStatus, bigint]> {
    return value.map((x)=>from_candid_tuple_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_LeadSource, bigint]>): Array<[LeadSource, bigint]> {
    return value.map((x)=>from_candid_tuple_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivityEntry>): Array<ActivityEntry> {
    return value.map((x)=>from_candid_ActivityEntry_n48(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FollowUpTaskPublic>): Array<FollowUpTaskPublic> {
    return value.map((x)=>from_candid_FollowUpTaskPublic_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfilePublic>): Array<UserProfilePublic> {
    return value.map((x)=>from_candid_UserProfilePublic_n53(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StatusHistoryEntry>): Array<StatusHistoryEntry> {
    return value.map((x)=>from_candid_StatusHistoryEntry_n9(_uploadFile, _downloadFile, x));
}
function to_candid_CreateLeadInput_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateLeadInput): _CreateLeadInput {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_CreateTaskInput_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateTaskInput): _CreateTaskInput {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_LeadFilter_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadFilter): _LeadFilter {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_LeadSource_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadSource): _LeadSource {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_LeadStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): _LeadStatus {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_RecurringType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecurringType): _RecurringType {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function to_candid_TaskType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskType): _TaskType {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserId | null): [] | [_UserId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    assignedTo: UserId;
    recurring: RecurringType;
    dueDate: Timestamp;
    taskType: TaskType;
    leadId: LeadId;
}): {
    title: string;
    assignedTo: _UserId;
    recurring: _RecurringType;
    dueDate: _Timestamp;
    taskType: _TaskType;
    leadId: _LeadId;
} {
    return {
        title: value.title,
        assignedTo: value.assignedTo,
        recurring: to_candid_RecurringType_n23(_uploadFile, _downloadFile, value.recurring),
        dueDate: value.dueDate,
        taskType: to_candid_TaskType_n25(_uploadFile, _downloadFile, value.taskType),
        leadId: value.leadId
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    source: LeadSource;
    campaign: string;
    name: string;
    tags: Array<string>;
    email: string;
    courseInterest: string;
    notes: string;
    dealValue: bigint;
    phone: string;
    assignedUserId?: UserId;
}): {
    source: _LeadSource;
    campaign: string;
    name: string;
    tags: Array<string>;
    email: string;
    courseInterest: string;
    notes: string;
    dealValue: bigint;
    phone: string;
    assignedUserId: [] | [_UserId];
} {
    return {
        source: to_candid_LeadSource_n29(_uploadFile, _downloadFile, value.source),
        campaign: value.campaign,
        name: value.name,
        tags: value.tags,
        email: value.email,
        courseInterest: value.courseInterest,
        notes: value.notes,
        dealValue: value.dealValue,
        phone: value.phone,
        assignedUserId: value.assignedUserId ? candid_some(value.assignedUserId) : candid_none()
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tag?: string;
    status?: LeadStatus;
    source?: LeadSource;
    campaign?: string;
    toDate?: Timestamp;
    fromDate?: Timestamp;
    assignedUserId?: UserId;
}): {
    tag: [] | [string];
    status: [] | [_LeadStatus];
    source: [] | [_LeadSource];
    campaign: [] | [string];
    toDate: [] | [_Timestamp];
    fromDate: [] | [_Timestamp];
    assignedUserId: [] | [_UserId];
} {
    return {
        tag: value.tag ? candid_some(value.tag) : candid_none(),
        status: value.status ? candid_some(to_candid_LeadStatus_n33(_uploadFile, _downloadFile, value.status)) : candid_none(),
        source: value.source ? candid_some(to_candid_LeadSource_n29(_uploadFile, _downloadFile, value.source)) : candid_none(),
        campaign: value.campaign ? candid_some(value.campaign) : candid_none(),
        toDate: value.toDate ? candid_some(value.toDate) : candid_none(),
        fromDate: value.fromDate ? candid_some(value.fromDate) : candid_none(),
        assignedUserId: value.assignedUserId ? candid_some(value.assignedUserId) : candid_none()
    };
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecurringType): {
    Weekly: null;
} | {
    None: null;
} | {
    Daily: null;
} | {
    Monthly: null;
} {
    return value == RecurringType.Weekly ? {
        Weekly: null
    } : value == RecurringType.None ? {
        None: null
    } : value == RecurringType.Daily ? {
        Daily: null
    } : value == RecurringType.Monthly ? {
        Monthly: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskType): {
    Sms: null;
} | {
    Email: null;
} | {
    Call: null;
} | {
    Whatsapp: null;
} | {
    Meeting: null;
} {
    return value == TaskType.Sms ? {
        Sms: null
    } : value == TaskType.Email ? {
        Email: null
    } : value == TaskType.Call ? {
        Call: null
    } : value == TaskType.Whatsapp ? {
        Whatsapp: null
    } : value == TaskType.Meeting ? {
        Meeting: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "Website";
    Website: null;
} | {
    __kind__: "ManualEntry";
    ManualEntry: null;
} | {
    __kind__: "LandingPage";
    LandingPage: null;
} | {
    __kind__: "FacebookAds";
    FacebookAds: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "CsvUpload";
    CsvUpload: null;
} | {
    __kind__: "ApiIntegration";
    ApiIntegration: null;
} | {
    __kind__: "Referral";
    Referral: null;
} | {
    __kind__: "GoogleAds";
    GoogleAds: null;
}): {
    Website: null;
} | {
    ManualEntry: null;
} | {
    LandingPage: null;
} | {
    FacebookAds: null;
} | {
    Other: string;
} | {
    CsvUpload: null;
} | {
    ApiIntegration: null;
} | {
    Referral: null;
} | {
    GoogleAds: null;
} {
    return value.__kind__ === "Website" ? {
        Website: value.Website
    } : value.__kind__ === "ManualEntry" ? {
        ManualEntry: value.ManualEntry
    } : value.__kind__ === "LandingPage" ? {
        LandingPage: value.LandingPage
    } : value.__kind__ === "FacebookAds" ? {
        FacebookAds: value.FacebookAds
    } : value.__kind__ === "Other" ? {
        Other: value.Other
    } : value.__kind__ === "CsvUpload" ? {
        CsvUpload: value.CsvUpload
    } : value.__kind__ === "ApiIntegration" ? {
        ApiIntegration: value.ApiIntegration
    } : value.__kind__ === "Referral" ? {
        Referral: value.Referral
    } : value.__kind__ === "GoogleAds" ? {
        GoogleAds: value.GoogleAds
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): {
    Won: null;
} | {
    Lost: null;
} | {
    ProposalSent: null;
} | {
    Contacted: null;
} | {
    Qualified: null;
} | {
    FollowUpScheduled: null;
} | {
    NewLead: null;
} | {
    Interested: null;
} | {
    NotInterested: null;
} {
    return value == LeadStatus.Won ? {
        Won: null
    } : value == LeadStatus.Lost ? {
        Lost: null
    } : value == LeadStatus.ProposalSent ? {
        ProposalSent: null
    } : value == LeadStatus.Contacted ? {
        Contacted: null
    } : value == LeadStatus.Qualified ? {
        Qualified: null
    } : value == LeadStatus.FollowUpScheduled ? {
        FollowUpScheduled: null
    } : value == LeadStatus.NewLead ? {
        NewLead: null
    } : value == LeadStatus.Interested ? {
        Interested: null
    } : value == LeadStatus.NotInterested ? {
        NotInterested: null
    } : value;
}
function to_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    SalesManager: null;
} | {
    Counselor: null;
} | {
    Telecaller: null;
} | {
    Admin: null;
} {
    return value == Role.SalesManager ? {
        SalesManager: null
    } : value == Role.Counselor ? {
        Counselor: null
    } : value == Role.Telecaller ? {
        Telecaller: null
    } : value == Role.Admin ? {
        Admin: null
    } : value;
}
function to_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CreateLeadInput>): Array<_CreateLeadInput> {
    return value.map((x)=>to_candid_CreateLeadInput_n27(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
